const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const pkg = require('../package.json');

let gitSha = 'unknown';
try {
  gitSha = execSync('git rev-parse --short HEAD', { cwd: __dirname }).toString().trim();
} catch {
  // no git repo available (e.g. some CI checkouts) — fall back to 'unknown'
}

const content = `// Auto-generated by scripts/generate-version.js at build time. Do not edit.
export const BUILD_VERSION = {
  version: '${pkg.version}',
  gitSha: '${gitSha}',
  buildTime: '${new Date().toISOString()}',
};
`;

fs.writeFileSync(path.join(__dirname, '../src/app/version.ts'), content);
console.log(`Generated src/app/version.ts (v${pkg.version} @ ${gitSha})`);
